- name: Rename host
  hosts: all
  become: yes
  tasks:
    - name: Set a hostname
      hostname:
        # always unique
        name: ip-{{ ansible_enp0s25.ipv4.address | replace('.','-') }}
        # easier to type hostname but not guaranteed to be unique
        # name: node{{ ansible_eth0.ipv4.address.split('.')[3][-1] }}
        # a little longer hostname, probably unique in most circumstances
        # name: node{{ ansible_eth0.ipv4.address.split('.')[3] }}
    - name: Unconditionally reboot the machine
      reboot:
        reboot_timeout: 3600