- hosts: all
  name: Add memory cgroup config to boot params
  tasks:
    - name: Add memory cgroup config to boot params
      replace:
        path: /boot/cmdline.txt
        regexp: '(rootwait)$'
        replace: '\1 cgroup_enable=memory cgroup_memory=1'